name: Trigger Jenkins Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger:
    runs-on: self-hosted  # 👈 runs on the local server

    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_TRIGGER_TOKEN: ${{ secrets.JENKINS_TRIGGER_TOKEN }}
        run: |
          echo "Triggering Jenkins pipeline..."
          curl -v -u "$JENKINS_USER:$JENKINS_TOKEN" \
               -X POST "$JENKINS_URL/job/my-pipeline/buildWithParameters?token=$JENKINS_TRIGGER_TOKEN" \
               --data-urlencode "BRANCH=${{ github.ref_name }}" \
               --data-urlencode "COMMIT=${{ github.sha }}"

