name: Trigger Jenkins Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger:
    runs-on: self-hosted  # 👈 runs on the local server

    steps:
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          HTTP_PROXY: ""
          HTTPS_PROXY: ""
          http_proxy: ""
          https_proxy: ""
          
        run: |
          echo "Triggering Jenkins pipeline..."
          curl -v -u "$JENKINS_USER:$JENKINS_TOKEN" \
               -X POST "$JENKINS_URL/job/test_pipeline/build"
              

